### ISSUE TITLE
Traffic bug

### ISSUE THREAD

**Issue by mohy06** [AndroidModLoader/GTASA_DrawDistance#1]
The traffic in the game is broking with this plugin you can see 20 or 30 ped and 10 or15 car in 1 hour gameplay (the traffic is very poor)

**Comment by AndroidModLoader** [comment]
Because you guys should stop tweaking everything to max, i will remove that if you continue doing this and crying in Discord

**Comment by N00BSAIB0T** [comment]
> Because you guys should stop tweaking everything to max, i will remove that if you continue doing this and crying in Discord
